spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

server.port: 8080

camunda:
  bpm:
    admin-user:
      password: ZSE$zse4
      id: admin
      first-name: Admin
      last-name: Admin
      email: pawga777@gmail.com
